apiVersion: certmanager.k8s.io/v1/alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
   acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kubes.pw@hatermail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}